//! Path-based HTTP router backed by a radix trie.
//!
//! The [`Router`] maps URL paths to [`MethodRouter`]s using the `matchit`
//! radix trie. Tower middleware can be attached at three levels:
//!
//! | Method | Scope |
//! |---|---|
//! | [`Router::layer`] | All requests (including 404s) |
//! | [`Router::route_layer`] | Only requests that match a route |
//! | [`MethodRouter::layer`] | Only the matched HTTP method handler |
//!
//! # Building a service
//!
//! After calling [`Router::with_state`] you receive a `Router<()>`. Call
//! [`Router::into_service`] to obtain a [`BoxCloneService`] with all layers
//! baked in, ready to be passed to `arvik_hyper::Server::serve_service`.
//!
//! `arvik_hyper::serve_app` calls `into_service()` internally.

use std::convert::Infallible;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll};

use arvik_core::handler::ErasedHandler;
use arvik_core::request::Request;
use arvik_core::response::{Response, ResponseBuilder};
use http::StatusCode;
use tower_layer::Layer;
use tower_service::Service;

use crate::layer::{BoxCloneService, LayerFn, apply_layers, into_layer_fn};
use crate::method_router::{MethodRouter, StateBound};
use crate::params::PathParams;
use crate::service::{ServiceHandler, StripPrefixService};

/// Shared sentinel labels for unmatched / fallback dispatch — avoids a heap
/// allocation per 404 under path-scanning load.
/// The matched leaf future plus the route pattern (inserted response-side).
pub(crate) type RouteLeafFut = Pin<Box<dyn Future<Output = Response> + Send>>;
pub(crate) type RouteLeaf = (RouteLeafFut, Arc<str>);

static FALLBACK_LABEL: std::sync::LazyLock<Arc<str>> =
    std::sync::LazyLock::new(|| Arc::from("__fallback"));
static UNMATCHED_LABEL: std::sync::LazyLock<Arc<str>> =
    std::sync::LazyLock::new(|| Arc::from("__unmatched"));

/// Metadata emitted by route macros and used by `collect_routes!`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RouteMeta {
    path: &'static str,
    method_mask: u16,
}

impl RouteMeta {
    /// Create route metadata from a normalized path and method bitmask.
    pub const fn new(path: &'static str, method_mask: u16) -> Self {
        Self { path, method_mask }
    }

    /// Return the normalized route path.
    pub const fn path(self) -> &'static str {
        self.path
    }

    /// Return the raw method bitmask.
    pub const fn method_mask(self) -> u16 {
        self.method_mask
    }
}

/// Assert that a collected macro route set has no duplicate method/path routes.
///
/// This function is `const` so proc macros can run the check during expansion.
pub const fn assert_no_route_conflicts(routes: &[RouteMeta]) {
    if route_conflict_count(routes) != 0 {
        panic!("duplicate route in collect_routes!");
    }
}

/// Return `1` when a collected macro route set has a duplicate route.
///
/// This intentionally caps at `1` so generated array-size assertions stay
/// simple and stable across Rust versions.
pub const fn route_conflict_count(routes: &[RouteMeta]) -> usize {
    let mut i = 0;
    while i < routes.len() {
        let mut j = i + 1;
        while j < routes.len() {
            if str_eq(routes[i].path, routes[j].path)
                && (routes[i].method_mask & routes[j].method_mask) != 0
            {
                return 1;
            }
            j += 1;
        }
        i += 1;
    }

    0
}

const fn str_eq(left: &str, right: &str) -> bool {
    let left = left.as_bytes();
    let right = right.as_bytes();
    if left.len() != right.len() {
        return false;
    }

    let mut i = 0;
    while i < left.len() {
        if left[i] != right[i] {
            return false;
        }
        i += 1;
    }

    true
}

/// A collected set of routes generated by `arvik::collect_routes!`.
pub trait CollectedRoutes<S> {
    /// Apply this route set to a router.
    fn apply(self, router: Router<S>) -> Router<S>;
}

impl<S, F> CollectedRoutes<S> for F
where
    F: FnOnce(Router<S>) -> Router<S>,
{
    fn apply(self, router: Router<S>) -> Router<S> {
        self(router)
    }
}

/// Extension type inserted by the router to record which route pattern matched.
///
/// Used by the `MatchedPath` extractor in `arvik-extract`.
#[derive(Debug, Clone)]
pub struct MatchedPathExt(pub Arc<str>);

// ── Router ───────────────────────────────────────────────────────────────────

/// Path-based HTTP router with radix trie matching and Tower middleware support.
///
/// # Quick start
///
/// ```rust,ignore
/// use arvik::{Router, get, post, State};
///
/// let app = Router::new()
///     .route("/", get(home))
///     .route("/users/{id}", get(get_user).post(create_user))
///     .layer(CorsLayer::permissive())         // all routes
///     .route_layer(TraceLayer::new_for_http()) // matched routes only
///     .with_state(AppState { /* ... */ });
///
/// arvik::serve_app("0.0.0.0:8080", app).await?;
/// ```
pub struct Router<S = ()> {
    trie: matchit::Router<usize>,
    routes: Vec<RouteEntry<S>>,
    fallback: Option<Box<dyn ErasedHandler<S>>>,
    /// Layers applied to **all** requests (applied by `into_service`).
    layers: Vec<LayerFn>,
    /// Layers applied to **matched-route** requests only (applied per-dispatch).
    route_layers: Vec<LayerFn>,
}

struct RouteEntry<S> {
    pattern: Arc<str>,
    method_router: MethodRouter<S>,
    /// Param names interned from the FIRST match — matchit owns the pattern
    /// strings for the router's lifetime, so later requests only refcount
    /// instead of re-allocating each key (`Arc::from(k)`).
    param_keys: std::sync::OnceLock<Vec<Arc<str>>>,
}

impl<S> RouteEntry<S> {
    fn new(path: &str, method_router: MethodRouter<S>) -> Self {
        Self {
            pattern: Arc::from(path),
            method_router,
            param_keys: std::sync::OnceLock::new(),
        }
    }
}

impl<S: Clone + Send + Sync + 'static> Router<S> {
    /// Create a new, empty `Router`.
    pub fn new() -> Self {
        Self {
            trie: matchit::Router::new(),
            routes: Vec::new(),
            fallback: None,
            layers: Vec::new(),
            route_layers: Vec::new(),
        }
    }

    /// Register a route.
    ///
    /// # Panics
    ///
    /// Panics on route conflicts (detected at startup, not at runtime).
    pub fn route(mut self, path: &str, method_router: MethodRouter<S>) -> Self {
        let idx = self.routes.len();
        if let Err(e) = self.trie.insert(path, idx) {
            panic!("Route conflict for `{path}`: {e}");
        }
        self.routes.push(RouteEntry::new(path, method_router));
        self
    }

    /// Register or merge a route emitted by proc macros.
    #[doc(hidden)]
    pub fn route_collected(mut self, path: &str, method_router: MethodRouter<S>) -> Self {
        if let Some(existing) = self
            .routes
            .iter_mut()
            .find(|entry| entry.pattern.as_ref() == path)
        {
            let current = std::mem::take(&mut existing.method_router);
            existing.method_router = current.merge(method_router);
            return self;
        }

        self.route(path, method_router)
    }

    /// Register a collected set of routes.
    pub fn routes<R>(self, routes: R) -> Self
    where
        R: CollectedRoutes<S>,
    {
        routes.apply(self)
    }

    /// Mount a sub-router under a path prefix (flatten strategy).
    ///
    /// Middleware attached to the sub-router (`.layer()` / `.route_layer()`)
    /// is preserved by folding it onto each flattened route. Note the
    /// flattening caveat: those layers run only on **matched** sub-router
    /// routes — unmatched paths in the prefix fall through to this router's
    /// fallback, like any other unmatched path.
    ///
    /// # Panics
    ///
    /// Panics if the sub-router has its own `.fallback()`: flattened routing
    /// cannot scope a fallback to the prefix. Set `.fallback()` on the outer
    /// router instead.
    pub fn nest(mut self, prefix: &str, other: Router<S>) -> Self {
        let prefix = prefix.trim_end_matches('/');
        if other.fallback.is_some() {
            panic!(
                "nest(\"{prefix}\"): the sub-router has a `.fallback()`, which cannot be \
                 scoped under a prefix when routes are flattened. Set `.fallback()` on the \
                 outer router instead."
            );
        }
        // Preserve middleware attached inside the sub-router by folding it
        // onto every flattened route's method-router layer stack:
        // handler ← method layers ← sub route_layers ← sub layers.
        let mut sub_layers = other.route_layers;
        sub_layers.extend(other.layers);
        for entry in other.routes {
            let path = entry.pattern.as_ref();
            let full = if path == "/" {
                format!("{prefix}/")
            } else {
                format!("{prefix}{path}")
            };
            let idx = self.routes.len();
            if let Err(e) = self.trie.insert(&full, idx) {
                panic!("Nested route conflict for `{full}`: {e}");
            }
            let mut method_router = entry.method_router;
            method_router.extend_layers(sub_layers.iter().cloned());
            self.routes.push(RouteEntry::new(&full, method_router));
        }
        self
    }

    /// Merge all routes from another router into this one.
    ///
    /// Middleware attached to the merged router is preserved by folding it
    /// onto each merged route; a merged `.fallback()` is adopted when this
    /// router has none.
    pub fn merge(mut self, other: Router<S>) -> Self {
        let mut sub_layers = other.route_layers;
        sub_layers.extend(other.layers);
        for entry in other.routes {
            let path = entry.pattern.as_ref();
            let idx = self.routes.len();
            if let Err(e) = self.trie.insert(path, idx) {
                panic!("Merge conflict for `{path}`: {e}");
            }
            let mut entry = entry;
            entry
                .method_router
                .extend_layers(sub_layers.iter().cloned());
            self.routes.push(entry);
        }
        if self.fallback.is_none() {
            self.fallback = other.fallback;
        }
        self
    }

    /// Set a custom fallback handler for unmatched paths (default: 404).
    pub fn fallback<H, T>(mut self, handler: H) -> Self
    where
        H: arvik_core::handler::Handler<T, S> + Clone + Send + Sync + 'static,
        T: 'static,
    {
        self.fallback = Some(arvik_core::handler::into_erased(handler));
        self
    }

    /// Mount a Tower service at an exact path.
    pub fn route_service<T>(self, path: &str, service: T) -> Self
    where
        T: Service<Request, Response = Response, Error = Infallible>
            + Clone
            + Send
            + Sync
            + 'static,
        T::Future: Send + 'static,
    {
        self.route(path, crate::any(ServiceHandler::new(service)))
    }

    /// Mount a Tower service at a path prefix (`{prefix}/*__rest`).
    pub fn nest_service<T>(self, prefix: &str, service: T) -> Self
    where
        T: Service<Request, Response = Response, Error = Infallible>
            + Clone
            + Send
            + Sync
            + 'static,
        T::Future: Send + 'static,
    {
        let prefix = normalize_service_prefix(prefix);
        let service = StripPrefixService::new(prefix.clone(), service);

        let mut router = self.route_service(&prefix, service.clone());
        if prefix != "/" {
            router = router.route_service(&format!("{prefix}/"), service.clone());
        }
        let path = if prefix == "/" {
            "/{*__rest}".to_string()
        } else {
            format!("{prefix}/{{*__rest}}")
        };
        router.route(&path, crate::any(ServiceHandler::new(service)))
    }

    // ── Layer methods ────────────────────────────────────────────────────────

    /// Apply a Tower middleware layer to **all routes** (including 404/405 responses).
    ///
    /// The last call to `.layer()` produces the **outermost** wrapper, so it
    /// processes the request first.
    ///
    /// ```rust,ignore
    /// Router::new()
    ///     .route("/", get(handler))
    ///     .layer(CorsLayer::permissive())   // ← processes every request
    /// ```
    pub fn layer<L>(mut self, layer: L) -> Self
    where
        L: Layer<BoxCloneService> + Clone + Send + Sync + 'static,
        L::Service: Service<Request, Response = Response, Error = Infallible>
            + Clone
            + Send
            + Sync
            + 'static,
        <L::Service as Service<Request>>::Future: Send + 'static,
    {
        self.layers.push(into_layer_fn(layer));
        self
    }

    /// Apply a Tower middleware layer to **matched routes only**.
    ///
    /// Unlike `layer`, this does not run on 404/405 responses.
    /// Processes the request **after** outer layers but **before** per-method layers.
    ///
    /// ```rust,ignore
    /// Router::new()
    ///     .route("/users/{id}", get(handler))
    ///     .route_layer(TraceLayer::new_for_http()) // only matched routes
    ///     .layer(CorsLayer::permissive())          // all routes
    /// ```
    pub fn route_layer<L>(mut self, layer: L) -> Self
    where
        L: Layer<BoxCloneService> + Clone + Send + Sync + 'static,
        L::Service: Service<Request, Response = Response, Error = Infallible>
            + Clone
            + Send
            + Sync
            + 'static,
        <L::Service as Service<Request>>::Future: Send + 'static,
    {
        self.route_layers.push(into_layer_fn(layer));
        self
    }

    // ── State binding ────────────────────────────────────────────────────────

    /// Bind application state, converting `Router<S>` → `Router<()>`.
    ///
    /// Call this once before passing your router to `serve_app` or
    /// `into_service`.
    pub fn with_state(self, state: S) -> Router<()> {
        let state = Arc::new(state);

        let routes: Vec<RouteEntry<()>> = self
            .routes
            .into_iter()
            .map(|entry| RouteEntry {
                pattern: entry.pattern,
                method_router: entry.method_router.with_state((*state).clone()),
                param_keys: entry.param_keys,
            })
            .collect();

        let fallback: Option<Box<dyn ErasedHandler<()>>> = self.fallback.map(|f| {
            Box::new(StateBound {
                inner: f,
                state: Arc::clone(&state),
            }) as Box<dyn ErasedHandler<()>>
        });

        Router {
            trie: self.trie,
            routes,
            fallback,
            layers: self.layers, // LayerFn is state-independent
            route_layers: self.route_layers,
        }
    }

    // ── Direct call (legacy / test path) ────────────────────────────────────

    /// Dispatch a request directly, **without** applying outer layers.
    ///
    /// This method exists for backward compatibility and internal testing.
    /// For production serving use `into_service` (via `serve_app`).
    pub async fn call(&self, mut req: Request, state: S) -> Response {
        let path = req.uri().path();

        match self.trie.at(path) {
            Ok(matched) => {
                let idx = *matched.value;
                let entry = &self.routes[idx];
                let pattern = Arc::clone(&entry.pattern);

                if !matched.params.is_empty() {
                    let mut pp = PathParams::new();
                    // Keys are interned on first sight of this route; values
                    // only allocate when decoding actually changed bytes.
                    let keys = entry
                        .param_keys
                        .get_or_init(|| matched.params.iter().map(|(k, _)| Arc::from(k)).collect());
                    for (idx, (_, v)) in matched.params.iter().enumerate() {
                        pp.push(Arc::clone(&keys[idx]), percent_decode(v).into_owned());
                    }
                    req.extensions_mut().insert(pp);
                }
                req.extensions_mut().insert(MatchedPathExt(pattern.clone()));

                let mut response = entry.method_router.call(req, state).await;
                response.extensions_mut().insert(MatchedPathExt(pattern));
                response
            }
            Err(_) => {
                if let Some(fb) = &self.fallback {
                    let mut response = fb.clone_box().call(req, state).await;
                    response
                        .extensions_mut()
                        .insert(MatchedPathExt(Arc::from("__fallback")));
                    return response;
                }
                let mut response = not_found();
                response
                    .extensions_mut()
                    .insert(MatchedPathExt(Arc::from("__unmatched")));
                response
            }
        }
    }
}

// ── Router<()> — Tower service conversion ───────────────────────────────────

impl Router<()> {
    /// Convert this router into a Tower [`BoxCloneService`] with all
    /// configured layers applied.
    ///
    /// Layer ordering:
    /// - `layers` (outer): wrap everything including 404s
    /// - `route_layers` (inner): wrap matched routes only
    /// - `MethodRouter::layers`: wrap matched method handlers only
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let svc = app.into_service();
    /// server.serve_service(svc).await?;
    /// ```
    pub fn into_service(self) -> BoxCloneService {
        let route_layers = self.route_layers;
        let outer_layers = self.layers;

        // Pre-fold the router-level route_layers into each entry ONCE, so the
        // per-request path clones a ready-made service instead of deep-cloning
        // the MethodRouter and re-wrapping every layer on every request.
        let layered_routes: Vec<Option<BoxCloneService>> = self
            .routes
            .iter()
            .map(|entry| {
                if route_layers.is_empty() {
                    None
                } else {
                    let base =
                        BoxCloneService::new(MethodRouterService(entry.method_router.clone()));
                    Some(apply_layers(base, &route_layers))
                }
            })
            .collect();

        // Inner core: route dispatch + prebuilt layered services
        let inner = Arc::new(RouterInner {
            trie: self.trie,
            routes: self.routes,
            fallback: self.fallback,
            layered_routes,
        });

        // Wrap in a clone-friendly Tower service
        let base = BoxCloneService::new(RouterService(inner));

        // Apply outer layers (first added = innermost)
        apply_layers(base, &outer_layers)
    }
}

impl<S: Clone + Send + Sync + 'static> Default for Router<S> {
    fn default() -> Self {
        Self::new()
    }
}

// ── RouterInner + RouterService ──────────────────────────────────────────────
//
// Split so the matchit trie (not Clone) can live behind an Arc.

struct RouterInner {
    trie: matchit::Router<usize>,
    routes: Vec<RouteEntry<()>>,
    fallback: Option<Box<dyn ErasedHandler<()>>>,
    /// Pre-folded `route_layer(method_router)` services, index-aligned with
    /// `routes`; `None` when the route has no router-level layers.
    layered_routes: Vec<Option<BoxCloneService>>,
}

impl RouterInner {
    /// Synchronous routing head (audit C3): trie match + parameter and
    /// MatchedPath extension inserts happen without entering an async state
    /// machine; only the matched leaf future is polled asynchronously.
    #[allow(clippy::result_large_err)] // Err carries the request back only on the rare unmatched path
    fn route(&self, mut req: Request) -> Result<RouteLeaf, Request> {
        let path = req.uri().path();

        match self.trie.at(path) {
            Ok(matched) => {
                let idx = *matched.value;
                let entry = &self.routes[idx];
                let pattern = Arc::clone(&entry.pattern);

                if !matched.params.is_empty() {
                    let mut pp = PathParams::new();
                    // Keys are interned on first sight of this route; values
                    // only allocate when decoding actually changed bytes.
                    let keys = entry
                        .param_keys
                        .get_or_init(|| matched.params.iter().map(|(k, _)| Arc::from(k)).collect());
                    for (idx, (_, v)) in matched.params.iter().enumerate() {
                        pp.push(Arc::clone(&keys[idx]), percent_decode(v).into_owned());
                    }
                    req.extensions_mut().insert(pp);
                }
                req.extensions_mut().insert(MatchedPathExt(pattern.clone()));

                // Cloning the prebuilt stack is a refcount-bump chain now that
                // MethodRouter shares its handlers behind an Arc.
                let fut: Pin<Box<dyn Future<Output = Response> + Send>> =
                    match self.layered_routes[idx].as_ref() {
                        Some(svc) => {
                            let svc = svc.clone();
                            Box::pin(async move { crate::layer::oneshot(svc, req).await })
                        }
                        None => {
                            // Clone is allocation-free (Arc'd internals).
                            let mr = entry.method_router.clone();
                            Box::pin(async move { mr.call(req, ()).await })
                        }
                    };
                Ok((fut, pattern))
            }
            Err(_) => Err(req),
        }
    }

    async fn dispatch(&self, req: Request) -> Response {
        match self.route(req) {
            Ok((fut, pattern)) => {
                let mut response = fut.await;
                response.extensions_mut().insert(MatchedPathExt(pattern));
                response
            }
            Err(req) => {
                if let Some(fb) = &self.fallback {
                    let mut response = fb.clone_box().call(req, ()).await;
                    response
                        .extensions_mut()
                        .insert(MatchedPathExt(std::sync::Arc::clone(&FALLBACK_LABEL)));
                    return response;
                }
                let mut response = not_found();
                response
                    .extensions_mut()
                    .insert(MatchedPathExt(std::sync::Arc::clone(&UNMATCHED_LABEL)));
                response
            }
        }
    }
}

// Tower service wrapper that shares RouterInner via Arc
struct RouterService(Arc<RouterInner>);

impl Clone for RouterService {
    fn clone(&self) -> Self {
        RouterService(Arc::clone(&self.0))
    }
}

impl Service<Request> for RouterService {
    type Response = Response;
    type Error = Infallible;
    type Future = Pin<Box<dyn Future<Output = Result<Response, Infallible>> + Send + 'static>>;

    fn poll_ready(&mut self, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: Request) -> Self::Future {
        let inner = Arc::clone(&self.0);
        Box::pin(async move { Ok(inner.dispatch(req).await) })
    }
}

// Tower service that wraps a MethodRouter<()> (used by route_layer path)
struct MethodRouterService(MethodRouter<()>);

impl Clone for MethodRouterService {
    fn clone(&self) -> Self {
        MethodRouterService(self.0.clone())
    }
}

impl Service<Request> for MethodRouterService {
    type Response = Response;
    type Error = Infallible;
    type Future = Pin<Box<dyn Future<Output = Result<Response, Infallible>> + Send + 'static>>;

    fn poll_ready(&mut self, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: Request) -> Self::Future {
        let mr = self.0.clone();
        Box::pin(async move { Ok(mr.call(req, ()).await) })
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

#[inline]
fn not_found() -> Response {
    ResponseBuilder::new()
        .status(StatusCode::NOT_FOUND)
        .header(http::header::CONTENT_TYPE, "text/plain; charset=utf-8")
        .text_static("Not Found")
}

fn normalize_service_prefix(prefix: &str) -> String {
    let trimmed = prefix.trim_end_matches('/');
    if trimmed.is_empty() {
        "/".to_string()
    } else if trimmed.starts_with('/') {
        trimmed.to_string()
    } else {
        format!("/{trimmed}")
    }
}

/// Percent-decode a URL path segment in-place (ASCII-only fast path).
/// Percent-decode a URL path segment (ASCII-only fast path).
///
/// Decoding happens *after* route matching, so decoded values are handed to
/// handlers verbatim. Sequences that would change segment structure or smuggle
/// control characters are therefore kept encoded: `%2F` (`/`) and `%5C` (`\`)
/// cannot introduce separators into captured params, and `%00`, `%0A`, `%0D`
/// stay escaped so NUL/CRLF cannot reach handlers, filesystems, or logs
/// through decoded values. Literal separators in the URL are unaffected.
fn percent_decode(input: &str) -> std::borrow::Cow<'_, str> {
    let bytes = input.as_bytes();
    if !bytes.contains(&b'%') {
        return std::borrow::Cow::Borrowed(input); // fast path: nothing to decode
    }
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let (Some(hi), Some(lo)) = (hex_nibble(bytes[i + 1]), hex_nibble(bytes[i + 2])) {
                let decoded = hi << 4 | lo;
                if matches!(decoded, b'/' | b'\\' | 0x00 | b'\n' | b'\r') {
                    // Preserve the escape — see doc comment.
                    out.extend_from_slice(&bytes[i..i + 3]);
                } else {
                    out.push(decoded);
                }
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    std::borrow::Cow::Owned(String::from_utf8(out).unwrap_or_else(|_| input.to_string()))
}

#[inline]
fn hex_nibble(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_percent_decode() {
        assert_eq!(percent_decode("hello%20world"), "hello world");
        assert_eq!(percent_decode("normal"), "normal");
        assert_eq!(percent_decode("100%25"), "100%");
    }

    #[test]
    fn percent_decode_keeps_structure_changing_escapes_encoded() {
        // Encoded separators must not become real separators post-match.
        assert_eq!(percent_decode("foo%2Fbar"), "foo%2Fbar");
        assert_eq!(percent_decode("a%5Cb"), "a%5Cb");
        // Control characters stay escaped.
        assert_eq!(percent_decode("a%00b"), "a%00b");
        assert_eq!(percent_decode("a%0d%0Ab"), "a%0d%0Ab");
        // Ordinary decodes still work.
        assert_eq!(percent_decode("a%2Eb"), "a.b");
        assert_eq!(percent_decode("%e2%82%ac"), "\u{20ac}");
        // Invalid UTF-8 falls back to the input unchanged.
        assert_eq!(percent_decode("%ff"), "%ff");
    }

    #[test]
    #[should_panic(expected = "Route conflict")]
    fn test_duplicate_route_panics() {
        async fn handler() -> &'static str {
            "test"
        }
        let _: Router<()> = Router::new()
            .route("/test", crate::get(handler))
            .route("/test", crate::get(handler));
    }

    #[test]
    fn test_static_routes() {
        async fn h() -> &'static str {
            "ok"
        }
        let _: Router<()> = Router::new()
            .route("/", crate::get(h))
            .route("/users", crate::get(h))
            .route("/about", crate::get(h));
    }

    #[test]
    fn test_param_routes() {
        async fn h() -> &'static str {
            "ok"
        }
        let _: Router<()> = Router::new()
            .route("/users/{id}", crate::get(h))
            .route("/users/{id}/posts/{post_id}", crate::get(h));
    }

    #[test]
    fn test_wildcard_routes() {
        async fn h() -> &'static str {
            "ok"
        }
        let _: Router<()> = Router::new()
            .route("/files/{*path}", crate::get(h))
            .route("/", crate::get(h));
    }

    #[test]
    fn test_nest() {
        async fn h() -> &'static str {
            "ok"
        }
        let sub = Router::new()
            .route("/", crate::get(h))
            .route("/{id}", crate::get(h));
        let _: Router<()> = Router::new().route("/", crate::get(h)).nest("/users", sub);
    }

    #[tokio::test]
    async fn nest_service_strips_prefix_and_preserves_query_and_original_uri() {
        use std::convert::Infallible;
        use std::future::{Ready, ready};
        use std::task::{Context, Poll};

        use arvik_core::{Body, OriginalUri, Request, ResponseBuilder};
        use tower_service::Service;

        #[derive(Clone)]
        struct EchoUri;

        impl Service<Request> for EchoUri {
            type Response = arvik_core::Response;
            type Error = Infallible;
            type Future = Ready<Result<Self::Response, Self::Error>>;

            fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
                Poll::Ready(Ok(()))
            }

            fn call(&mut self, req: Request) -> Self::Future {
                let original = req
                    .extensions()
                    .get::<OriginalUri>()
                    .map(|uri| uri.0.to_string())
                    .unwrap_or_default();
                ready(Ok(ResponseBuilder::new().text(format!(
                    "{}|{}",
                    req.uri(),
                    original
                ))))
            }
        }

        let mut app = Router::new()
            .nest_service("/static", EchoUri)
            .into_service();

        let req = Request::new(
            http::Request::builder()
                .uri("/static/app.css?v=1")
                .body(Body::empty())
                .unwrap(),
        );
        let res = app.call(req).await.unwrap();
        assert_eq!(
            res.into_body().to_string().await.unwrap(),
            "/app.css?v=1|/static/app.css?v=1"
        );
    }

    #[tokio::test]
    async fn nest_service_handles_mount_root_and_slash() {
        use std::convert::Infallible;
        use std::future::{Ready, ready};
        use std::task::{Context, Poll};

        use arvik_core::{Body, Request, ResponseBuilder};
        use tower_service::Service;

        #[derive(Clone)]
        struct EchoPath;

        impl Service<Request> for EchoPath {
            type Response = arvik_core::Response;
            type Error = Infallible;
            type Future = Ready<Result<Self::Response, Self::Error>>;

            fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
                Poll::Ready(Ok(()))
            }

            fn call(&mut self, req: Request) -> Self::Future {
                ready(Ok(ResponseBuilder::new().text(req.uri().path().to_string())))
            }
        }

        let mut app = Router::new()
            .nest_service("/static", EchoPath)
            .into_service();

        let req = Request::new(
            http::Request::builder()
                .uri("/static")
                .body(Body::empty())
                .unwrap(),
        );
        let res = app.call(req).await.unwrap();
        assert_eq!(res.into_body().to_string().await.unwrap(), "/");

        let req = Request::new(
            http::Request::builder()
                .uri("/static/")
                .body(Body::empty())
                .unwrap(),
        );
        let res = app.call(req).await.unwrap();
        assert_eq!(res.into_body().to_string().await.unwrap(), "/");
    }

    #[tokio::test]
    async fn matched_route_is_available_on_response_extensions() {
        async fn h() -> &'static str {
            "ok"
        }

        let mut app = Router::new()
            .route("/users/{id}", crate::get(h))
            .into_service();
        let req = Request::new(
            http::Request::builder()
                .uri("/users/42")
                .body(arvik_core::Body::empty())
                .unwrap(),
        );

        let res = app.call(req).await.unwrap();
        assert_eq!(
            res.extensions()
                .get::<MatchedPathExt>()
                .map(|matched| matched.0.as_ref()),
            Some("/users/{id}")
        );
    }

    #[tokio::test]
    async fn mid_segment_params_expose_their_declared_names() {
        async fn h(req: arvik_core::Request) -> String {
            let params = req.extensions().get::<PathParams>().unwrap();
            format!(
                "{}:{}",
                params.get("id").unwrap_or("MISSING"),
                params.get("tag").unwrap_or("MISSING")
            )
        }

        // matchit supports mid-segment params; positional pattern parsing used
        // to misalign these (audit L2).
        let mut app = Router::new()
            .route("/images/img{id}.png/{tag}", crate::get(h))
            .into_service();
        let req = Request::new(
            http::Request::builder()
                .uri("/images/img7.png/nature")
                .body(arvik_core::Body::empty())
                .unwrap(),
        );

        let res = app.call(req).await.unwrap();
        let text = String::from_utf8(res.into_body().to_bytes().await.unwrap().to_vec()).unwrap();
        assert_eq!(text, "7:nature");
    }

    #[tokio::test]
    async fn param_route_decodes_values() {
        async fn h(req: arvik_core::Request) -> String {
            let params = req.extensions().get::<PathParams>().unwrap();
            format!(
                "{}:{}",
                params.get("id").unwrap(),
                params.get("path").unwrap()
            )
        }

        let mut app = Router::new()
            .route("/users/{id}/files/{*path}", crate::get(h))
            .into_service();
        let req = Request::new(
            http::Request::builder()
                .uri("/users/42/files/a%20b/report")
                .body(arvik_core::Body::empty())
                .unwrap(),
        );

        let res = app.call(req).await.unwrap();
        assert_eq!(res.into_body().to_string().await.unwrap(), "42:a b/report");
    }

    #[test]
    fn test_merge() {
        async fn h() -> &'static str {
            "ok"
        }
        let api = Router::new().route("/users", crate::get(h));
        let admin = Router::new().route("/admin", crate::get(h));
        let _: Router<()> = api.merge(admin);
    }

    #[test]
    #[should_panic(expected = "Merge conflict")]
    fn test_merge_conflict_panics() {
        async fn h() -> &'static str {
            "ok"
        }
        let a = Router::new().route("/users", crate::get(h));
        let b = Router::new().route("/users", crate::get(h));
        let _: Router<()> = a.merge(b);
    }

    // ── nest/merge middleware preservation (audit H3) ────────────────────────

    /// Layer that appends its tag to the `x-mark` response header.
    #[derive(Clone)]
    struct MarkLayer(&'static str);

    impl Layer<BoxCloneService> for MarkLayer {
        type Service = MarkService;

        fn layer(&self, inner: BoxCloneService) -> Self::Service {
            MarkService { inner, tag: self.0 }
        }
    }

    #[derive(Clone)]
    struct MarkService {
        inner: BoxCloneService,
        tag: &'static str,
    }

    impl Service<Request> for MarkService {
        type Response = Response;
        type Error = Infallible;
        type Future = Pin<Box<dyn Future<Output = Result<Response, Infallible>> + Send + 'static>>;

        fn poll_ready(&mut self, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }

        fn call(&mut self, req: Request) -> Self::Future {
            let cloned = self.inner.clone();
            let mut inner = std::mem::replace(&mut self.inner, cloned);
            let value = self.tag.parse().unwrap();
            Box::pin(async move {
                let mut res = inner
                    .call(req)
                    .await
                    .unwrap_or_else(|infallible| match infallible {});
                res.headers_mut().append("x-mark", value);
                Ok(res)
            })
        }
    }

    async fn marked_handler() -> &'static str {
        "inner"
    }

    fn get_req(path: &str) -> Request {
        Request::new(
            http::Request::builder()
                .method(http::Method::GET)
                .uri(path)
                .body(arvik_core::Body::empty())
                .unwrap(),
        )
    }

    #[tokio::test]
    async fn nest_preserves_subrouter_layers_and_route_layers() {
        let sub = Router::new()
            .route("/inner", crate::get(marked_handler))
            .route_layer(MarkLayer("route"))
            .layer(MarkLayer("wide"));
        let app: Router<()> = Router::new().nest("/sub", sub);

        // Matched nested route carries both sub-router layers (outer first).
        let res = app.call(get_req("/sub/inner"), ()).await;
        assert_eq!(res.status(), StatusCode::OK);
        let marks: Vec<_> = res
            .headers()
            .get_all("x-mark")
            .iter()
            .filter_map(|v| v.to_str().ok())
            .collect();
        assert_eq!(marks, vec!["route", "wide"]);
    }

    #[tokio::test]
    async fn nested_layers_do_not_leak_outside_the_prefix_or_to_unmatched_paths() {
        async fn outer_handler() -> &'static str {
            "outer"
        }
        let sub = Router::new()
            .route("/inner", crate::get(marked_handler))
            .layer(MarkLayer("sub"));
        let app: Router<()> = Router::new()
            .route("/own", crate::get(outer_handler))
            .nest("/sub", sub);

        // Parent's own route is untouched by sub-router layers.
        let res = app.call(get_req("/own"), ()).await;
        assert!(res.headers().get("x-mark").is_none());

        // Unmatched path under the prefix: no sub-router layer runs (404).
        let res = app.call(get_req("/sub/missing"), ()).await;
        assert_eq!(res.status(), StatusCode::NOT_FOUND);
        assert!(res.headers().get("x-mark").is_none());
    }

    #[test]
    #[should_panic(expected = "cannot be scoped")]
    fn nest_rejects_subrouter_fallback_instead_of_dropping_it() {
        async fn h() -> &'static str {
            "ok"
        }
        let sub: Router<()> = Router::new().route("/inner", crate::get(h)).fallback(h);
        let _: Router<()> = Router::new().nest("/sub", sub);
    }

    #[tokio::test]
    async fn merge_preserves_merged_router_layers() {
        let sub = Router::new()
            .route("/a", crate::get(marked_handler))
            .route_layer(MarkLayer("merged"));
        let app: Router<()> = Router::new().merge(sub);

        let res = app.call(get_req("/a"), ()).await;
        assert_eq!(res.status(), StatusCode::OK);
        let marks: Vec<&str> = res
            .headers()
            .get_all("x-mark")
            .iter()
            .filter_map(|v| v.to_str().ok())
            .collect();
        assert_eq!(marks, vec!["merged"]);
    }
}
