[package]
name = "arvik-hyper"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
readme.workspace = true
description = "Hyper server integration for the Arvik web framework"

[dependencies]
arvik-core     = { workspace = true }
arvik-router   = { workspace = true }
arvik-tls      = { workspace = true, optional = true }
tokio          = { workspace = true }
hyper          = { workspace = true }
hyper-util     = { workspace = true }
http           = { workspace = true }
http-body      = { workspace = true }
http-body-util = { workspace = true }
bytes          = { workspace = true }
tracing        = { workspace = true }
tower-service  = { workspace = true }
socket2        = { workspace = true }
tokio-metrics  = { workspace = true, optional = true }

[features]
default = ["http1", "http2"]
http1 = ["hyper/http1", "hyper-util/http1"]
http2 = ["hyper/http2", "hyper-util/http2"]
tls = ["dep:arvik-tls", "arvik-tls/rustls"]
tls-hot-reload = ["tls", "arvik-tls/tls-hot-reload"]
native-tls = ["dep:arvik-tls", "arvik-tls/native-tls"]
native-tls-vendored = ["native-tls", "arvik-tls/native-tls-vendored"]
runtime-metrics = ["dep:tokio-metrics"]
