[package]
name = "arvik"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
readme.workspace = true
description = "Arvik — Fast, Typed, and Fearless Web Framework for Rust"

[dependencies]
arvik-core    = { workspace = true }
arvik-hyper   = { workspace = true }
arvik-router  = { workspace = true }
arvik-extract = { workspace = true }
arvik-middleware = { workspace = true }
arvik-tls     = { workspace = true, optional = true }
arvik-static  = { workspace = true, optional = true, default-features = false }
arvik-macros  = { workspace = true, optional = true }
arvik-test    = { workspace = true, optional = true }
arvik-config  = { workspace = true, optional = true }
arvik-ws      = { workspace = true, optional = true }
arvik-sse        = { workspace = true, optional = true }
tokio         = { workspace = true }
http          = { workspace = true }
bytes         = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
tracing       = { workspace = true }
tracing-subscriber = { workspace = true }
cookie           = { workspace = true }
futures-util     = { workspace = true }
tower-layer   = { workspace = true }
tower-service = { workspace = true }
uuid = { workspace = true }

[features]
default = []
http1 = ["arvik-hyper/http1"]
http2 = ["arvik-hyper/http2"]
tls = ["dep:arvik-tls", "arvik-hyper/tls", "arvik-tls/rustls"]
tls-hot-reload = ["tls", "arvik-hyper/tls-hot-reload", "arvik-tls/tls-hot-reload"]
native-tls = ["dep:arvik-tls", "arvik-hyper/native-tls", "arvik-tls/native-tls"]
native-tls-vendored = ["native-tls", "arvik-hyper/native-tls-vendored", "arvik-tls/native-tls-vendored"]
static-files = ["dep:arvik-static", "arvik-static/fs"]
embedded-static = ["static-files", "arvik-static/embed"]
macros = ["dep:arvik-macros"]
test-utils = ["dep:arvik-test"]
config = ["dep:arvik-config"]
config-hot-reload = ["config", "arvik-config/hot-reload"]
ws = ["dep:arvik-ws", "arvik-test?/ws"]
sse = ["dep:arvik-sse"]

[dev-dependencies]
trybuild = { workspace = true }
