[package]
name = "arvik-static"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
readme.workspace = true
description = "Static file serving for the Arvik web framework"

[dependencies]
arvik-core        = { workspace = true }
bytes             = { workspace = true }
futures-util      = { workspace = true }
http              = { workspace = true }
http-body-util    = { workspace = true }
httpdate          = { workspace = true }
mime              = { workspace = true }
mime_guess        = { workspace = true }
percent-encoding = { workspace = true }
rust-embed        = { workspace = true, optional = true }
tokio             = { workspace = true, optional = true }
tokio-util        = { workspace = true, optional = true }
tower-service     = { workspace = true }

[features]
default = ["fs"]
fs = ["dep:tokio", "dep:tokio-util"]
embed = ["dep:rust-embed"]

[dev-dependencies]
tempfile = { workspace = true }
